# Generated by Django 2.2.1 on 2019-05-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='horarios_func',
            new_name='horario_func',
        ),
    ]
